"""Add major and enrollment status to student

Revision ID: 3d56902388ef
Revises: f8454dbf3f01
Create Date: 2026-02-22 00:24:07.080564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d56902388ef'
down_revision = 'f8454dbf3f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('is_enrolled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('is_enrolled')
        batch_op.drop_column('major')

    # ### end Alembic commands ###
